# Site settings
title: on Rails, аудит, экспертиза, Agile
tag_text: Проблемы с Ruby on Rails?
description: Экспертиза Ruby on Rails проектов

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
